/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telas;

import control.AtendimentoC;
import control.UbsC;
import dao.PacienteDao;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import model.Agenda;
import model.Atendimento;
import model.Paciente;
import util.Yagami;
import view.popups.InsAgenda;

/**
 * Tela de Cadastro de Atendimento
 * @author Juan Galvão
 */
public class CadAtendimento extends javax.swing.JInternalFrame {
    // Variável para o contador
    protected Timer timer = new Timer();
    Agenda ag, agendaReal;
    DefaultComboBoxModel dlm = new DefaultComboBoxModel();
    List<Paciente> listPaciente;
    PacienteDao pdao = new PacienteDao();
    int idPaciente;
    
    /**
     * Creates new form CadAtendimento
     */
    public CadAtendimento() {
        initComponents();
        setLocation(100, 100); 
        UbsC.CONTROL.listComboBox(cmbUbs);
        Yagami.YG.setPublicObject(new Agenda());
        
        
        idPaciente = Yagami.YG.getPublicId();
        //ativarCadastro(false);
        getPaciente();
        
        // Loop que atualzia a cada 50 milisegundos
        timer.schedule( new TimerTask() {
            @Override
            public void run() {
               // Garantir que o texto do campo endereço esteja correto
               //txtAgenda.setText("0");
               ag = (Agenda) Yagami.YG.getPublicObject();
               txtAgenda.setText(ag.getData_ag() + " - " + ag.getHora_ag());
            }
         }, 0, 50);
        
    }
    
    private void getPaciente() {
        //String teste = "COMPONENTES...";
        List<Paciente> pac = pdao.listar(true, idPaciente);
        txtCodigo.setText(String.valueOf(pac.get(0).getId()));
        txtNome.setText(pac.get(0).getNome());
        txtConvenio.setText(pac.get(0).getConvenio());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForm = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        cmbBloco = new javax.swing.JComboBox();
        txtConvenio = new javax.swing.JTextField();
        txtAgenda = new javax.swing.JTextField();
        cmbUbs = new javax.swing.JComboBox();
        cmbConsulta = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();
        lblProtocolo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblConvenio = new javax.swing.JLabel();
        lblBloco = new javax.swing.JLabel();
        lblAgenda = new javax.swing.JLabel();
        lblUbs = new javax.swing.JLabel();
        lblTipoConsulta = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        panelComandos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro de Atendimento");
        setName("ATE000"); // NOI18N

        panelForm.setBackground(new java.awt.Color(245, 245, 245));
        panelForm.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNome.setEditable(false);

        txtCodigo.setEditable(false);

        cmbBloco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bloco 1", "Bloco 2", "Bloco 3" }));

        txtConvenio.setEditable(false);

        txtAgenda.setBackground(new java.awt.Color(204, 204, 255));
        txtAgenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAgendaFocusGained(evt);
            }
        });

        cmbUbs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UBS" }));

        cmbConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ortopedia", "Cardiologia", "Pneumo", "Ginecologista", "Pediatria", "Neurologia" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblProtocolo.setText("Protocolo: 0");

        lblNome.setText("Nome:");

        lblCodigo.setText("Código:");

        lblConvenio.setText("Convênio:");

        lblBloco.setText("Bloco:");

        lblAgenda.setText("Agenda:");

        lblUbs.setText("UBS:");

        lblTipoConsulta.setText("Tipo de Consulta:");

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipoConsulta)
                    .addComponent(lblAgenda)
                    .addComponent(lblNome)
                    .addComponent(lblBloco)
                    .addComponent(txtNome)
                    .addComponent(cmbBloco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAgenda)
                    .addComponent(cmbConsulta, 0, 190, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProtocolo)
                    .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCodigo)
                        .addComponent(txtCodigo)
                        .addComponent(txtConvenio)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbUbs, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUbs)
                    .addComponent(lblConvenio))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConvenio)
                    .addComponent(lblBloco))
                .addGap(3, 3, 3)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgenda)
                    .addComponent(lblUbs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUbs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoConsulta)
                    .addComponent(lblProtocolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lblTitle.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTitle.setText("Cadastrar Atendimento");

        panelComandos.setBackground(new java.awt.Color(247, 247, 247));
        panelComandos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Operações");

        jLabel2.setText("Sair");

        jLabel3.setText("ESC");

        javax.swing.GroupLayout panelComandosLayout = new javax.swing.GroupLayout(panelComandos);
        panelComandos.setLayout(panelComandosLayout);
        panelComandosLayout.setHorizontalGroup(
            panelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComandosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComandosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(panelComandosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(12, 12, 12))
        );
        panelComandosLayout.setVerticalGroup(
            panelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComandosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(panelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgendaFocusGained
        // TODO add your handling code here:
        txtCodigo.requestFocus();
        new InsAgenda(null, true).setVisible(true);
        txtCodigo.requestFocus();
    }//GEN-LAST:event_txtAgendaFocusGained

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        agendaReal = (Agenda) Yagami.YG.getPublicObject();
        Atendimento at = new Atendimento();
        at.setBloco_atual(cmbBloco.getSelectedItem().toString());
        at.setBloco_inicial(at.getBloco_atual());
        at.setData_at(ag.getData_ag());
        at.setHorario(ag.getHora_ag());
        at.setFk_medico(1); // TO DO
        at.setFk_patendimento(1); // TO DO
        at.setFk_ubs(cmbUbs.getSelectedIndex() + 1);
        at.setObservacoes("00");
        at.setTipo_atendimento(cmbConsulta.getSelectedItem().toString());
        AtendimentoC.CONTROL.create(at);
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbBloco;
    private javax.swing.JComboBox cmbConsulta;
    private javax.swing.JComboBox cmbUbs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblConvenio;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProtocolo;
    private javax.swing.JLabel lblTipoConsulta;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUbs;
    private javax.swing.JPanel panelComandos;
    private javax.swing.JPanel panelForm;
    private javax.swing.JTextField txtAgenda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConvenio;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
